# Form implementation generated from reading ui file 'AKD.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AccessKey(object):
    def setupUi(self, AccessKey):
        AccessKey.setObjectName("AccessKey")
        AccessKey.resize(400, 300)
        AccessKey.setStyleSheet("background : qlineargradient(spread:pad, x1:0.466, y1:0, x2:0.568, y2:1, stop:0 rgba(38, 150, 250, 255), stop:1 rgba(255, 76, 255, 255))")
        self.textBrowser = QtWidgets.QTextBrowser(AccessKey)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 361, 261))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border-radius : 10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.AK = QtWidgets.QLabel(AccessKey)
        self.AK.setGeometry(QtCore.QRect(140, 51, 121, 31))
        self.AK.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 18pt \"Segoe UI\";")
        self.AK.setObjectName("AK")
        self.AKLE = QtWidgets.QLineEdit(AccessKey)
        self.AKLE.setGeometry(QtCore.QRect(100, 110, 201, 22))
        self.AKLE.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.AKLE.setObjectName("AKLE")
        self.AKS = QtWidgets.QLabel(AccessKey)
        self.AKS.setGeometry(QtCore.QRect(90, 152, 221, 31))
        self.AKS.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.AKS.setObjectName("AKS")
        self.GAK = QtWidgets.QPushButton(AccessKey)
        self.GAK.setGeometry(QtCore.QRect(131, 211, 141, 41))
        self.GAK.setStyleSheet("background-color: rgba(39, 244, 255, 200);\n"
"border-radius: 20px;")
        self.GAK.setObjectName("GAK")

        self.retranslateUi(AccessKey)
        QtCore.QMetaObject.connectSlotsByName(AccessKey)

    def retranslateUi(self, AccessKey):
        _translate = QtCore.QCoreApplication.translate
        AccessKey.setWindowTitle(_translate("AccessKey", "Dialog"))
        self.AK.setText(_translate("AccessKey", "Access Key"))
        self.AKS.setText(_translate("AccessKey", "Status : "))
        self.GAK.setText(_translate("AccessKey", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AccessKey = QtWidgets.QDialog()
    ui = Ui_AccessKey()
    ui.setupUi(AccessKey)
    AccessKey.show()
    sys.exit(app.exec())
